import os
import re
import json

# Paths
DATA_DIR = "/Users/purew/Desktop/android-os/apps/Bilibili/data"
AUTHOR_DATA_FILE = os.path.join(DATA_DIR, "authorData.ts")
VIDEO_FILES = [
    os.path.join(DATA_DIR, "videoData.ts"),
    os.path.join(DATA_DIR, "rankingData.ts"),
    os.path.join(DATA_DIR, "hotData.ts"),
    os.path.join(DATA_DIR, "recommendData.ts"),
]

def extract_mid_location_map():
    print("Scanning video files for locations...")
    mid_loc_map = {}
    
    # Regex to capture raw objects or at least mid and pub_location proximity
    # Since the files are large, we can't just parse the whole file as JSON easily (it's TS).
    # But the 'raw' object is usually standardized JSON string inside the TS file.
    # Pattern: "pub_location": "xxx" ... "mid": 123
    # OR "mid": 123 ... "pub_location": "xxx"
    # They are within the same 'raw' object.
    
    # A safer approach without full parsing:
    # 1. Read file.
    # 2. Extract contents of `raw: { ... }`.
    # 3. Parse that content as JSON (if possible) or regex match within it.
    
    for fw in VIDEO_FILES:
        if not os.path.exists(fw):
            continue
            
        with open(fw, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Strategy: find all "raw": { ... } blocks
        # This is tricky with nested braces. 
        # Simpler Strategy for this specific data structure:
        # The files are generated by json.dumps, so "raw": { ... } is on one line or consistently formatted?
        # In gen_ranking_data.py, indent=4 is used. 'raw' might key might be followed by object.
        # But 'raw' is just a key in the TS object. 
        
        # Let's rely on the fact that these are JSON exports mostly.
        # extract everything between `export const ... = [` and `];`
        # Then parse as JSON.
        
        # Try matching array export first (videoData, hotData)
        match_array = re.search(r'export const \w+\s*(?::\s*[^=]+)?\s*=\s*(\[.*\]);', content, re.DOTALL)
        
        # Try matching object export (rankingData)
        match_object = re.search(r'export const \w+\s*(?::\s*[^=]+)?\s*=\s*({.*});', content, re.DOTALL)

        json_str = None
        is_object = False

        if match_array:
            json_str = match_array.group(1)
        elif match_object:
            json_str = match_object.group(1)
            is_object = True
        
        if json_str:
            try:
                data = json.loads(json_str)
                
                # Helper to process a list of videos
                def process_video_list(vid_list):
                    for item in vid_list:
                        raw = item.get('raw')
                        if not raw: continue
                        
                        # Check for mid
                        mid = None
                        if 'owner' in raw and 'mid' in raw['owner']:
                            mid = raw['owner']['mid']
                        elif 'mid' in raw:
                            mid = raw['mid']
                            
                        # Check for location
                        loc = raw.get('pub_location')
                        
                        if mid and loc:
                            mid_loc_map[mid] = loc

                if is_object:
                    # rankingData is Record<string, Video[]>
                    for key, video_list in data.items():
                        if isinstance(video_list, list):
                            process_video_list(video_list)
                else:
                    # videoData is Video[]
                    if isinstance(data, list):
                        process_video_list(data)
                        
            except Exception as e:
                print(f"Failed to parse JSON in {fw}: {e}")
                pass
    
    print(f"Found {len(mid_loc_map)} locations.")
    return mid_loc_map

def update_author_data(mid_loc_map):
    if not os.path.exists(AUTHOR_DATA_FILE):
        print("Author data file not found.")
        return

    with open(AUTHOR_DATA_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Update Interface
    if "location?: string;" not in content:
        content = content.replace("    mid: number;", "    mid: number;\n    location?: string;")
        print("Updated Interface.")

    # 2. Update Data
    # Extract the JSON part
    match = re.search(r'(export const AUTHOR_DATA: Record<number, UserInfo> = )({.*})(;)', content, re.DOTALL)
    if not match:
        print("Could not find AUTHOR_DATA object.")
        return

    prefix = match.group(1)
    json_str = match.group(2)
    suffix = match.group(3)

    try:
        authors = json.loads(json_str)
        updated_count = 0
        
        for mid_str, author in authors.items():
            mid = int(mid_str)
            if mid in mid_loc_map:
                if 'location' not in author:
                    author['location'] = mid_loc_map[mid]
                    updated_count += 1
            
            # Also if we have location in author but not in map (unlikely if we just scan), keep it.
        
        print(f"Updated {updated_count} authors with location.")
        
        # Reconstruct file
        new_json_str = json.dumps(authors, ensure_ascii=False, indent=4)
        new_content = content.replace(json_str, new_json_str)
        
        with open(AUTHOR_DATA_FILE, 'w', encoding='utf-8') as f:
            f.write(new_content)
        
        print("Successfully wrote back to authorData.ts")
        
    except Exception as e:
        print(f"Error processing author data: {e}")

if __name__ == "__main__":
    mapping = extract_mid_location_map()
    update_author_data(mapping)
