#!/usr/bin/env python3
"""
Generate explicit (one-by-one) WeChat action tasks as Python classes.

Input:
  bench_env/generated_task/action_tasks/spec.jsonl
  (generated by scripts/build_action_task_specs.py)

Output:
  bench_env/generated_task/wechat_action_tasks/tasks.py

Why:
  User asked to "一个个写出这些任务"，先写微信，并且必须是 state judge（不是 VLM）。

Notes:
  Some action ids only affect local React component state (not exposed in __SIM__.getState()
  and not changing route). Those are NOT judgeable via state/route, so we skip them.
"""

from __future__ import annotations

import json
import re
import pprint
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "bench_env/generated_task/action_tasks/spec.jsonl"
OUT_PATH = ROOT / "bench_env/generated_task/wechat_action_tasks/tasks.py"


SKIP_ACTION_IDS = {
    # Only updates local component state (pin dots), no route/state change.
    "faceToFace.pin.input",
    "faceToFace.pin.delete.submit",
}


PAREN_RE = re.compile(r"[（(]([^）)]+)[）)]")


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = (line or "").strip()
        if not line:
            continue
        obj = json.loads(line)
        if isinstance(obj, dict):
            out.append(obj)
    return out


def extract_expected_from_label(label: str) -> str | None:
    if not label:
        return None
    m = PAREN_RE.findall(label)
    if not m:
        return None
    return (m[-1] or "").strip() or None


def infer_wechat_judge(spec: dict[str, Any]) -> dict[str, Any]:
    action = spec.get("action") if isinstance(spec.get("action"), dict) else {}
    action_id = str(action.get("id") or "")
    behavior = str(action.get("behavior") or "")
    label = str(action.get("label") or "")

    # 1) Chat actions
    if action_id == "chat.pat.send":
        return {"kind": "wechat_chat_pat", "id_param": "id"}

    if behavior == "toggle":
        if action_id.startswith("chatInfo.item.") and action_id.endswith(".toggle"):
            key = action_id[len("chatInfo.item.") : -len(".toggle")]
            field_map = {"muted": "isMuted", "sticky": "isSticky", "alert": "isAlert"}
            field = field_map.get(key)
            if field:
                return {"kind": "toggle_chat_field", "id_param": "id", "field": field}

        if action_id.startswith("friendSettings.item.") and action_id.endswith(".toggle"):
            key = action_id[len("friendSettings.item.") : -len(".toggle")]
            field_map = {"star": "isStarred", "blacklist": "isBlacklisted"}
            field = field_map.get(key)
            if field:
                return {"kind": "toggle_contact_field", "id_param": "id", "field": field}

        if action_id.startswith("friendPermissionsDetail.item.") and action_id.endswith(".toggle"):
            key = action_id[len("friendPermissionsDetail.item.") : -len(".toggle")]
            field_map = {"hideMyMoments": "hideMyMoments", "hideTheirMoments": "hideTheirMoments"}
            field = field_map.get(key)
            if field:
                return {"kind": "toggle_contact_field", "id_param": "id", "field": field}

        if action_id.startswith("wechatSports.") and action_id.endswith(".toggle"):
            rest = action_id[len("wechatSports.") : -len(".toggle")]
            parts = [p for p in rest.split(".") if p]
            if parts and parts[0] == "privacy":
                parts = parts[1:]
            if parts:
                return {"kind": "toggle_field", "path": "user.settings.accessibility.wechatSports." + ".".join(parts)}

        if action_id.startswith("settings.") and action_id.endswith(".toggle"):
            core = action_id[len("settings.") : -len(".toggle")]
            parts = [p for p in core.split(".") if p]
            if not parts:
                return {"kind": "state_diff", "prefix": "user.settings"}
            section = parts[0]
            tail = parts[1:]

            if section == "accessibility" and len(tail) >= 2:
                # settings.accessibility.tencentNews.dnd.toggle -> user.settings.accessibility.tencentNews.dnd
                plugin = tail[0]
                field = ".".join(tail[1:])
                return {"kind": "toggle_field", "path": f"user.settings.accessibility.{plugin}.{field}"}

            if section == "discover" and tail[:1] == ["item"] and len(tail) >= 2:
                # settings.discover.item.visible.toggle -> user.settings.discover[id].visible
                field = tail[1]
                return {"kind": "toggle_discover_item_field", "id_param": "id", "field": field}

            if section == "careMode":
                return {"kind": "toggle_field", "path": "user.settings.modes.care"}
            if section == "minorMode":
                return {"kind": "toggle_field", "path": "user.settings.modes.minor"}

            if section == "privacy":
                if tail[:1] == ["addMe"] and len(tail) >= 2:
                    return {"kind": "toggle_field", "path": f"user.settings.privacy.addMeMethods.{tail[1]}"}
                if tail == ["moments", "strangerTen"]:
                    return {"kind": "toggle_field", "path": "user.settings.privacy.momentsStrangerTen"}
                if tail:
                    return {"kind": "toggle_field", "path": "user.settings.privacy." + ".".join(tail)}
                return {"kind": "state_diff", "prefix": "user.settings.privacy"}

            if section == "general" and tail:
                if tail[:2] == ["darkMode", "followSystem"]:
                    return {"kind": "toggle_field", "path": "user.settings.general.followSystem"}
                if tail[:2] == ["translation", "autoTranslate"]:
                    return {"kind": "toggle_field", "path": "user.settings.general.autoTranslate"}
                if tail[:1] in (["media"], ["audio"]) and len(tail) >= 2:
                    return {"kind": "toggle_field", "path": "user.settings.general." + ".".join(tail[1:])}
                return {"kind": "toggle_field", "path": "user.settings.general." + ".".join(tail)}

            if section == "chat" and tail:
                return {"kind": "toggle_field", "path": "user.settings.chat." + ".".join(tail)}

            if section == "notifications" and tail:
                return {"kind": "toggle_field", "path": "user.settings.notifications." + ".".join(tail)}

            return {"kind": "state_diff", "prefix": "user.settings"}

    if behavior == "select":
        expected = extract_expected_from_label(label)
        if action_id.startswith("settings.notifications.sound.select.") and expected:
            return {"kind": "set_field", "path": "user.settings.notifications.notificationSound", "expected": expected}
        if action_id.startswith("settings.notifications.incomingRingtone.select.") and expected:
            return {"kind": "set_field", "path": "user.settings.notifications.incomingRingtone", "expected": expected}
        if action_id.startswith("settings.privacy.moments.range.select.") and expected:
            return {"kind": "set_field", "path": "user.settings.privacy.momentsRange", "expected": expected}
        if action_id.startswith("settings.general.darkMode.mode.select."):
            if "深色" in label:
                return {"kind": "multi_set", "checks": [
                    {"path": "user.settings.general.followSystem", "expected": False},
                    {"path": "user.settings.general.darkMode", "expected": True},
                ]}
            if "普通" in label:
                return {"kind": "multi_set", "checks": [
                    {"path": "user.settings.general.followSystem", "expected": False},
                    {"path": "user.settings.general.darkMode", "expected": False},
                ]}
        return {"kind": "state_diff", "prefix": "user.settings"}

    # submit/input/other: handle known ones
    if action_id == "friendSettings.menu.blacklistConfirm.submit":
        return {"kind": "set_contact_field", "id_param": "id", "field": "isBlacklisted", "expected": True}

    if action_id == "settings.privacy.authorization.menu.confirm.submit":
        return {"kind": "remove_authorized_app", "id_param": "id"}

    if action_id.endswith(".enable.submit") and action_id.startswith("settings.accessibility."):
        # settings.accessibility.wechatSports.enable.submit -> enabled=True
        core = action_id[len("settings.accessibility.") : -len(".enable.submit")]
        return {"kind": "set_field", "path": f"user.settings.accessibility.{core}.enabled", "expected": True}

    if action_id.endswith(".disable.submit") and action_id.startswith("settings.accessibility."):
        core = action_id[len("settings.accessibility.") : -len(".disable.submit")]
        return {"kind": "set_field", "path": f"user.settings.accessibility.{core}.enabled", "expected": False}

    if action_id in {"moments.post.submit", "moments.postText.submit"}:
        return {"kind": "list_len_increased", "path": "moments"}

    if action_id in {"profile.name.submit"}:
        return {"kind": "field_changed", "path": "user.name"}
    if action_id in {"profile.signature.submit"}:
        return {"kind": "field_changed", "path": "user.signature"}
    if action_id in {"profile.gender.submit"}:
        return {"kind": "field_changed", "path": "user.gender"}
    if action_id in {"profile.pat.submit"}:
        return {"kind": "field_changed", "path": "user.pat"}

    if action_id in {"settings.notifications.sound.submit"}:
        return {"kind": "field_changed", "path": "user.settings.notifications.notificationSound"}

    if action_id in {"settings.general.darkMode.submit"}:
        return {"kind": "state_diff", "prefix": "user.settings.general"}

    # last resort (still state-based, but weaker)
    return {"kind": "state_diff", "prefix": ""}  # any app-state diff


def render_py(specs: list[dict[str, Any]]) -> str:
    # Build explicit class definitions
    header = """\"\"\"Auto-generated WeChat action tasks (explicit classes).

Generated by scripts/generate_wechat_action_tasks_module.py

IMPORTANT:
- Source spec: bench_env/generated_task/action_tasks/spec.jsonl
- Runtime module: bench_env/generated_task/wechat_action_tasks/tasks.py
- These tasks are discoverable under app='wechat_action_tasks' (TaskRegistry).
- They open target app 'wechat' in setup().
- Judge is STATE-based (route/apps state), not VLM.
\"\"\"

from __future__ import annotations

from typing import Any, ClassVar

from bench_env.task.base import BaseTask, BaseApp
from bench_env.task.judge import JudgeInput, StateComparator


class _WechatActionTaskBase(BaseTask):
    \"\"\"Base for generated tasks; name starts with _ to hide from registry.\"\"\"

    app: ClassVar[str] = \"__wechat_action_tasks_base__\"
    template: ClassVar[str] = \"\"
    complexity: ClassVar[int] = 1
    parameters: ClassVar[dict[str, dict[str, Any]]] = {}
    optimal_paths: ClassVar[list[list[Any]]] = []
    note: ClassVar[str] = \"\"

    _judge: ClassVar[dict[str, Any]] = {}

    async def setup(self, env: Any):  # type: ignore[override]
        await self._prepare(env)
        state = await env.get_state()
        if self.sampler:
            result = self.sampler.sample(state, task=self)
            for k, v in result.params.items():
                if k in self._user_params:
                    continue
                self.params[k] = v
        # Always open wechat
        await env.open_app(\"wechat\", wait_stable=True)
        return await env.get_observation()

    def _app_init(self, input: JudgeInput) -> dict[str, Any]:
        return (input.apps_init or {}).get(\"wechat\", {}) or {}

    def _app_curr(self, input: JudgeInput) -> dict[str, Any]:
        return (input.apps or {}).get(\"wechat\", {}) or {}

    def _get(self, app_state: dict[str, Any], path: str) -> Any:
        return BaseApp.get_by_path(app_state, path, None)

    def _find_by_id(self, items: Any, id_field: str, wanted: str) -> dict[str, Any] | None:
        if not wanted or not isinstance(items, list):
            return None
        for x in items:
            if isinstance(x, dict) and str(x.get(id_field) or \"\") == str(wanted):
                return x
        return None

    def check_goals(self, input: JudgeInput) -> list[dict[str, Any]]:
        j = dict(self._judge or {})
        kind = str(j.get(\"kind\") or \"\").strip()

        init_app = self._app_init(input)
        curr_app = self._app_curr(input)

        if kind == \"toggle_chat_field\":
            chat_id = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            field = str(j.get(\"field\") or \"\")
            b = self._find_by_id(init_app.get(\"chats\", []), \"id\", chat_id) or {}
            a = self._find_by_id(curr_app.get(\"chats\", []), \"id\", chat_id) or {}
            before, after = b.get(field), a.get(field)
            return [{\"field\": f\"chats[{chat_id}].{field}\", \"expected\": \"toggled\", \"actual\": {\"init\": before, \"curr\": after}, \"passed\": before != after}]

        if kind == \"set_chat_field\":
            chat_id = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            field = str(j.get(\"field\") or \"\")
            expected = j.get(\"expected\")
            a = self._find_by_id(curr_app.get(\"chats\", []), \"id\", chat_id) or {}
            actual = a.get(field)
            return [{\"field\": f\"chats[{chat_id}].{field}\", \"expected\": expected, \"actual\": actual, \"passed\": actual == expected}]

        if kind == \"toggle_contact_field\":
            wxid = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            field = str(j.get(\"field\") or \"\")
            b = self._find_by_id(init_app.get(\"contacts\", []), \"wxid\", wxid) or {}
            a = self._find_by_id(curr_app.get(\"contacts\", []), \"wxid\", wxid) or {}
            before, after = b.get(field), a.get(field)
            return [{\"field\": f\"contacts[{wxid}].{field}\", \"expected\": \"toggled\", \"actual\": {\"init\": before, \"curr\": after}, \"passed\": before != after}]

        if kind == \"set_contact_field\":
            wxid = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            field = str(j.get(\"field\") or \"\")
            expected = j.get(\"expected\")
            a = self._find_by_id(curr_app.get(\"contacts\", []), \"wxid\", wxid) or {}
            actual = a.get(field)
            return [{\"field\": f\"contacts[{wxid}].{field}\", \"expected\": expected, \"actual\": actual, \"passed\": actual == expected}]

        if kind == \"toggle_discover_item_field\":
            item_id = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            field = str(j.get(\"field\") or \"\")
            before = self._get(init_app, f\"user.settings.discover.{item_id}.{field}\")
            after = self._get(curr_app, f\"user.settings.discover.{item_id}.{field}\")
            return [{\"field\": f\"user.settings.discover[{item_id}].{field}\", \"expected\": \"toggled\", \"actual\": {\"init\": before, \"curr\": after}, \"passed\": before != after}]

        if kind == \"set_discover_item_field\":
            item_id = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            field = str(j.get(\"field\") or \"\")
            expected = j.get(\"expected\")
            actual = self._get(curr_app, f\"user.settings.discover.{item_id}.{field}\")
            return [{\"field\": f\"user.settings.discover[{item_id}].{field}\", \"expected\": expected, \"actual\": actual, \"passed\": actual == expected}]

        if kind == \"toggle_field\":
            path = str(j.get(\"path\") or \"\")
            before = self._get(init_app, path)
            after = self._get(curr_app, path)
            return [{\"field\": path, \"expected\": \"toggled\", \"actual\": {\"init\": before, \"curr\": after}, \"passed\": before != after}]

        if kind == \"set_field\":
            path = str(j.get(\"path\") or \"\")
            expected = j.get(\"expected\")
            actual = self._get(curr_app, path)
            return [{\"field\": path, \"expected\": expected, \"actual\": actual, \"passed\": actual == expected}]

        if kind == \"multi_set\":
            checks = j.get(\"checks\") if isinstance(j.get(\"checks\"), list) else []
            out = []
            for c in checks:
                if not isinstance(c, dict):
                    continue
                path = str(c.get(\"path\") or \"\")
                expected = c.get(\"expected\")
                actual = self._get(curr_app, path)
                out.append({\"field\": path, \"expected\": expected, \"actual\": actual, \"passed\": actual == expected})
            return out if out else [{\"field\": \"multi_set\", \"expected\": \"non-empty\", \"actual\": checks, \"passed\": False}]

        if kind == \"remove_authorized_app\":
            app_id = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            init_ids = {str(x.get(\"id\")) for x in (init_app.get(\"authorizedApps\") or []) if isinstance(x, dict)}
            curr_ids = {str(x.get(\"id\")) for x in (curr_app.get(\"authorizedApps\") or []) if isinstance(x, dict)}
            passed = (app_id in init_ids) and (app_id not in curr_ids)
            return [{\"field\": \"authorizedApps\", \"expected\": f\"removed {app_id}\", \"actual\": {\"init\": list(init_ids)[:5], \"curr\": list(curr_ids)[:5]}, \"passed\": passed}]

        if kind == \"list_len_increased\":
            path = str(j.get(\"path\") or \"\")
            before = self._get(init_app, path) or []
            after = self._get(curr_app, path) or []
            passed = isinstance(before, list) and isinstance(after, list) and len(after) > len(before)
            return [{\"field\": path, \"expected\": \"len increased\", \"actual\": {\"init\": len(before) if isinstance(before, list) else None, \"curr\": len(after) if isinstance(after, list) else None}, \"passed\": passed}]

        if kind == \"field_changed\":
            path = str(j.get(\"path\") or \"\")
            before = self._get(init_app, path)
            after = self._get(curr_app, path)
            return [{\"field\": path, \"expected\": \"changed\", \"actual\": {\"init\": before, \"curr\": after}, \"passed\": before != after}]

        if kind == \"wechat_chat_pat\":
            chat_id = str(getattr(self.p, str(j.get(\"id_param\") or \"id\"), \"\") or \"\")
            b = self._find_by_id(init_app.get(\"chats\", []), \"id\", chat_id) or {}
            a = self._find_by_id(curr_app.get(\"chats\", []), \"id\", chat_id) or {}
            bm = b.get(\"messages\") or []
            am = a.get(\"messages\") or []
            # Success: messages increased and contains system message with '拍了拍'
            grew = isinstance(bm, list) and isinstance(am, list) and len(am) > len(bm)
            has_pat = any(isinstance(m, dict) and str(m.get(\"type\")) == \"system\" and \"拍了拍\" in str(m.get(\"content\") or \"\") for m in (am if isinstance(am, list) else []))
            return [{\"field\": f\"chats[{chat_id}].messages\", \"expected\": \"new system pat message\", \"actual\": {\"grew\": grew, \"has_pat\": has_pat}, \"passed\": bool(grew and has_pat)}]

        # Default: any wechat state diff
        diffs = StateComparator.diff_states(init_app if isinstance(init_app, dict) else {}, curr_app if isinstance(curr_app, dict) else {}, prefix=\"\")
        return [{\"field\": \"wechat.state_changed\", \"expected\": \"diffs>0\", \"actual\": f\"diffs={len(diffs)}\", \"passed\": len(diffs) > 0}]

    def get_expected_changes(self, input: JudgeInput) -> list[str]:
        \"\"\"Return fully-qualified expected change prefixes (apps.wechat.*).\"\"\"
        j = dict(self._judge or {})
        kind = str(j.get(\"kind\") or \"\").strip()

        if kind in {\"toggle_chat_field\", \"set_chat_field\", \"wechat_chat_pat\"}:
            return [\"apps.wechat.chats\"]
        if kind in {\"toggle_contact_field\", \"set_contact_field\"}:
            return [\"apps.wechat.contacts\"]
        if kind in {\"toggle_discover_item_field\", \"set_discover_item_field\"}:
            return [\"apps.wechat.user.settings.discover\"]
        if kind in {\"toggle_field\", \"set_field\", \"field_changed\"}:
            path = str(j.get(\"path\") or \"\").strip()
            return [f\"apps.wechat.{path}\" if path else \"apps.wechat\"]
        if kind == \"multi_set\":
            checks = j.get(\"checks\") if isinstance(j.get(\"checks\"), list) else []
            out: list[str] = []
            for c in checks:
                if not isinstance(c, dict):
                    continue
                p = str(c.get(\"path\") or \"\").strip()
                if p:
                    out.append(f\"apps.wechat.{p}\")
            return out or [\"apps.wechat.user.settings\"]
        if kind == \"remove_authorized_app\":
            return [\"apps.wechat.authorizedApps\"]
        if kind == \"list_len_increased\":
            p = str(j.get(\"path\") or \"\").strip()
            return [f\"apps.wechat.{p}\" if p else \"apps.wechat\"]
        if kind == \"state_diff\":
            prefix = str(j.get(\"prefix\") or \"\").strip()
            return [f\"apps.wechat.{prefix}\" if prefix else \"apps.wechat\"]

        return [\"apps.wechat\"]

"""

    def _pretty_action_label(raw: str) -> str:
        s = str(raw or "").strip()
        # common patterns: "xxx：开关" / "xxx: 开关"
        s = s.replace("：开关", "").replace(": 开关", "").replace(":开关", "")
        return s

    def _emit_class(
        *,
        base_class_name: str,
        template: str,
        complexity: int,
        params: dict[str, Any],
        optimal_paths: list,
        judge: dict[str, Any],
        add_discover_sampler: bool,
    ) -> list[str]:
        out: list[str] = []
        out.append(f"\n\nclass {base_class_name}(_WechatActionTaskBase):")
        out.append(f"    template = {template!r}")
        out.append("    app = 'wechat_action_tasks'")
        out.append(f"    complexity = {int(complexity)}")
        out.append(f"    parameters = {pprint.pformat(params, width=120, sort_dicts=False)}")
        out.append(f"    optimal_paths = {pprint.pformat(optimal_paths, width=120, sort_dicts=False)}")
        out.append(f"    _judge = {pprint.pformat(judge, width=120, sort_dicts=False)}")
        if add_discover_sampler:
            out.append("")
            out.append("    def _sample_wechat_discover_id(self, env_state: dict) -> str | None:")
            out.append("        try:")
            out.append("            discover = (((env_state.get('apps') or {}).get('wechat') or {}).get('user') or {}).get('settings', {}).get('discover', {})")
            out.append("            if isinstance(discover, dict) and discover:")
            out.append("                keys = list(discover.keys())")
            out.append("                return self.sampler.rng.choice(keys) if self.sampler else keys[0]")
            out.append("        except Exception:")
            out.append("            return None")
            out.append("        return None")
        return out

    emitted_classes = 0
    lines = [header]
    for spec in specs:
        action = spec.get("action") if isinstance(spec.get("action"), dict) else {}
        action_id = str(action.get("id") or "")
        if action_id in SKIP_ACTION_IDS:
            continue

        base_class_name = str(spec.get("class_name") or "").strip() or "Task"
        # Make sure class_name is a valid identifier (spec should already be)
        base_class_name = re.sub(r"[^0-9A-Za-z_]+", "_", base_class_name)
        if base_class_name[0].isdigit():
            base_class_name = "T_" + base_class_name

        label = str(action.get("label") or action_id)
        route = ""
        if isinstance(spec.get("target"), dict):
            route = str((spec.get("target") or {}).get("routePath") or "")
        base_template = f"在微信中执行动作「{label}」" + (f"（页面 {route}）" if route else "")

        # Parameters: start from spec, then refine common 'id' sampling based on action id.
        params = spec.get("parameters") if isinstance(spec.get("parameters"), dict) else {}
        params = dict(params)

        # Refine wechat id sampling depending on the action
        if "id" in (action.get("paramsSchema") or {}):
            if action_id.startswith("friend") or action_id.startswith("friendPermissionsDetail."):
                params["id"] = {
                    "type": "string",
                    "source": "apps.wechat.contacts[wxid]",
                    "default": "wxid_blank_001",
                    "description": "联系人 wxid",
                }
            elif action_id.startswith("chat") or action_id.startswith("chatInfo."):
                params["id"] = {
                    "type": "string",
                    "source": "apps.wechat.chats[id]",
                    "default": "wxid_blank_001",
                    "description": "聊天 id（对方 wxid）",
                }
            elif action_id.startswith("settings.privacy.authorization."):
                params["id"] = {
                    "type": "string",
                    "source": "apps.wechat.authorizedApps[id]",
                    "default": "tencent_news",
                    "description": "授权应用 id",
                }

        # Discover item toggles need object key sampler (TaskSampler can't sample dict keys)
        judge = infer_wechat_judge(spec)
        if judge.get("kind") in {"toggle_discover_item_field", "set_discover_item_field"}:
            params["id"] = {
                "type": "string",
                "sampler": "_sample_wechat_discover_id",
                "default": "moments",
                "description": "发现管理条目 id（discover key）",
            }

        shortest_len = spec.get("shortestLength")
        complexity = int(shortest_len) if isinstance(shortest_len, (int, float)) and shortest_len else 2
        opt = spec.get("optimal_paths") if isinstance(spec.get("optimal_paths"), list) else []

        kind = str(judge.get("kind") or "")
        add_discover_sampler = judge.get("kind") in {"toggle_discover_item_field", "set_discover_item_field"}

        # "补齐"：for toggle-type tasks, generate TWO explicit tasks: set to True and set to False.
        if kind in {"toggle_chat_field", "toggle_contact_field", "toggle_discover_item_field", "toggle_field"}:
            pretty = _pretty_action_label(label)
            for expected in (True, False):
                suffix = "to_true" if expected else "to_false"
                class_name = f"{base_class_name}__{suffix}"
                # Convert toggle judge -> set judge
                if kind == "toggle_chat_field":
                    j2 = {"kind": "set_chat_field", "id_param": judge.get("id_param", "id"), "field": judge.get("field"), "expected": expected}
                elif kind == "toggle_contact_field":
                    j2 = {"kind": "set_contact_field", "id_param": judge.get("id_param", "id"), "field": judge.get("field"), "expected": expected}
                elif kind == "toggle_discover_item_field":
                    j2 = {"kind": "set_discover_item_field", "id_param": judge.get("id_param", "id"), "field": judge.get("field"), "expected": expected}
                else:  # toggle_field
                    j2 = {"kind": "set_field", "path": judge.get("path"), "expected": expected}

                verb = "开启" if expected else "关闭"
                tpl = f"在微信中将「{pretty}」设置为{verb}" + (f"（页面 {route}）" if route else "")
                lines.extend(_emit_class(
                    base_class_name=class_name,
                    template=tpl,
                    complexity=complexity,
                    params=params,
                    optimal_paths=opt,
                    judge=j2,
                    add_discover_sampler=add_discover_sampler,
                ))
                emitted_classes += 1
            continue

        # Non-toggle tasks: generate 1:1
        lines.extend(_emit_class(
            base_class_name=base_class_name,
            template=base_template,
            complexity=complexity,
            params=params,
            optimal_paths=opt,
            judge=judge,
            add_discover_sampler=add_discover_sampler,
        ))
        emitted_classes += 1

    # Embed a footer comment for sanity checks
    lines.append(f"\n# GENERATED_TASK_CLASS_COUNT={emitted_classes}\n")
    return "\n".join(lines) + "\n"


def main() -> None:
    if not SPEC_PATH.exists():
        raise SystemExit(f"spec not found: {SPEC_PATH}")

    specs_all = read_jsonl(SPEC_PATH)
    wechat_specs = [s for s in specs_all if s.get("target_app") == "wechat"]

    # Filter out non-judgeable local-only actions
    out_specs = []
    skipped = 0
    for s in wechat_specs:
        action = s.get("action") if isinstance(s.get("action"), dict) else {}
        aid = str(action.get("id") or "")
        if aid in SKIP_ACTION_IDS:
            skipped += 1
            continue
        out_specs.append(s)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    text = render_py(out_specs)
    OUT_PATH.write_text(text, encoding="utf-8")
    # Count emitted classes (exclude the base class)
    emitted = sum(1 for line in text.splitlines() if line.startswith("class ")) - 1  # minus base class
    print(f"[OK] wrote {emitted} wechat task classes to {OUT_PATH} (source specs {len(out_specs)}, skipped {skipped})")


if __name__ == "__main__":
    main()

